version: 2.1

jobs:
  job:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: |
          # echo Hello, World!aaa
          sleep 100

  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ppSeqivtyonaXj3iW5uKk2c/2M0JhtCU797RA+OqDwA"
      - run: |
          # echo Hello, World!!
          sleep 10

  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: |
          # echo Hello, World!
  ubuntu:
    docker:
      - image: cimg/base:current
      #- image: ubuntu:latest
    resource_class: small
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  C:
    jobs:
      - test
      - ubuntu
  B:
    jobs:
      - build
  A:
    jobs:
      - build
      - job:
          requires:
            - build

daily-run-workflow:
  triggers:
    - schedule:
        cron: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,23,25,23,30,33,35,37,40,43,45,47,50,52,55,58 * * * *"
        filters:
          branches:
            only:
              - main
  jobs:
    - test
    - job
    - build

min-run-workflow:
  triggers:
    - schedule:
        cron: "0,2,3,5,8,10,12,15,17,20,23,25,23,30,33,35,37,40,43,45,47,50,52,55,58 * * * *"
        filters:
          branches:
            only:
              - main
  jobs:
    - test
    - job
    - build
